(ns sushi-machine.random-name)

(def adjektiv ["hedonistisk"
               "morsom"
               "teit"
               "sexy"
               "genial"
               "psykotisk"
               "esende"
               "barsk"
               "deilig"
               "snodig"
               "modig"
               "flau"
               "allmektig"
               "stygg"
               "gul"
               "klok"
               "syk"
               "klein"
               "skitten"
               "farlig"
               "blind"
               "kvalm"
               "lysten"
               "full"
               "desperat"
               "sint"
               "ond"
               "skarp"
               "lat"])

(def substantiv ["rev"
                 "elg"
                 "sau"
                 "munk"
                 "nisse"
                 "mor"
                 "trikk"
                 "bybane"
                 "ku"
                 "katt"
                 "ugle"
                 "kodemann"
                 "politiker"
                 "dust"
                 "maskin"
                 "automat"
                 "kollega"
                 "nabo"
                 "mann"
                 "dame"
                 "programmerer"
                 "selger"])

(def verb ["hopper"
           "sniker"
           "smyger"
           "snoker"
           "titter"
           "danser"
           "koder"
           "knoter"
           "synger"
           "soper"
           "spiser"
           "suger"
           "brygger"
           "bader"
           "stripper"
           "koker"
           "fjaser"
           "bakser"
           "mikser"
           "jukser"
           "baker"
           "drikker"
           "sniffer"
           "hoster"])

(defn gen-random-name []
  (->> [adjektiv substantiv verb]
       (map rand-nth)
       (clojure.string/join '-)))
